trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
  - job: 'CI'
    strategy:
      matrix:
        linux-stable:
          rustup_toolchain: stable,
          image_name: 'ubuntu-18.04'
        linux-nightly:
          rustup_toolchain: nightly
          image_name: 'ubuntu-18.04'
        windows-stable:
          rustup_toolchain: stable
          image_name: 'windows-latest'
        apple-stable:
          rustup_toolchain: stable
          image_name: 'macOS-10.15'

    pool:
        vmImage: $(image_name)

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Install Rust
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        displayName: Install Rust
        condition: eq( variables['Agent.OS'], 'Windows_NT' )

      - script: cargo build
        displayName: Build

      - script: cargo test
        displayName: Test
