[package]
name = "feather-protocol"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
smallbox = "0.8"

[build-dependencies]
feather-packet-parser = { path = "parser" }
async-std = { version = "1.1", features = ["attributes"] }

[workspace]
members = [".", "parser"]
