[package]
name = "feather-protocol"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
smallbox = "0.8"

[workspace]
members = [".", "parser"]
